--------------------------------------------------------------------------------
-- FORMATTER FINAL BOSS : Oracle SQL / PL-SQL One-Script Stress Set
-- 목적:
--   1) 자동 포맷팅(CTRL+SHIFT+F) 내구성 검증
--   2) 깊은 괄호 중첩, CASE/DECODE, analytic, CONNECT BY, MODEL, JSON/XML,
--      dynamic SQL, OPEN FOR, PIVOT/UNPIVOT, MERGE, multitable INSERT,
--      comments, hints, q-quote, bind-like placeholder, scalar subquery,
--      lateral/cross apply, nested CTE, quoted string, operator wrap 검증
--   3) "이것만 통과하면 화면 정렬이 거의 완벽" 수준의 최종보스 케이스
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- CLEANUP
--------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW qt_fmt_emp_v';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE qt_fmt_pkg';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE qt_fmt_pair_tab';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE qt_fmt_pair_ot';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 AND SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE qt_fmt_audit PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE qt_fmt_bonus PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE qt_fmt_emp PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE qt_fmt_dept PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

--------------------------------------------------------------------------------
-- BASE OBJECTS
--------------------------------------------------------------------------------
CREATE TABLE qt_fmt_dept
(
    dept_id         NUMBER         CONSTRAINT qt_fmt_dept_pk PRIMARY KEY,
    parent_dept_id  NUMBER,
    dept_code       VARCHAR2(30)   NOT NULL,
    dept_name       VARCHAR2(100)  NOT NULL,
    region_cd       VARCHAR2(10),
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP
);
/

CREATE TABLE qt_fmt_emp
(
    emp_id          NUMBER         CONSTRAINT qt_fmt_emp_pk PRIMARY KEY,
    dept_id         NUMBER         NOT NULL,
    mgr_emp_id      NUMBER,
    emp_name        VARCHAR2(100)  NOT NULL,
    login_name      VARCHAR2(100)  NOT NULL,
    email_addr      VARCHAR2(200),
    salary          NUMBER(12, 2),
    bonus_pct       NUMBER(5, 2),
    hire_dt         DATE,
    status_cd       VARCHAR2(20),
    job_title       VARCHAR2(100),
    note_text       CLOB,
    json_doc        CLOB CHECK (json_doc IS JSON),
    xml_doc         XMLTYPE,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT qt_fmt_emp_fk1 FOREIGN KEY (dept_id) REFERENCES qt_fmt_dept (dept_id)
);
/

CREATE TABLE qt_fmt_bonus
(
    emp_id          NUMBER         NOT NULL,
    bonus_year      NUMBER(4)      NOT NULL,
    bonus_type      VARCHAR2(30)   NOT NULL,
    amount          NUMBER(12, 2),
    calc_note       VARCHAR2(4000),
    CONSTRAINT qt_fmt_bonus_pk PRIMARY KEY (emp_id, bonus_year, bonus_type),
    CONSTRAINT qt_fmt_bonus_fk1 FOREIGN KEY (emp_id) REFERENCES qt_fmt_emp (emp_id)
);
/

CREATE TABLE qt_fmt_audit
(
    audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name     VARCHAR2(100),
    action_name     VARCHAR2(100),
    key_text        VARCHAR2(400),
    payload_text    CLOB,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

--------------------------------------------------------------------------------
-- OBJECT TYPE FOR TABLE() / MULTISET / CAST / COLLECT
--------------------------------------------------------------------------------
CREATE OR REPLACE TYPE qt_fmt_pair_ot AS OBJECT
(
    k VARCHAR2(100),
    v VARCHAR2(4000)
);
/

CREATE OR REPLACE TYPE qt_fmt_pair_tab AS TABLE OF qt_fmt_pair_ot;
/

--------------------------------------------------------------------------------
-- DATA
--------------------------------------------------------------------------------
INSERT ALL
    INTO qt_fmt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_cd) VALUES (10, NULL, 'HQ',   'Headquarters',   'KR')
    INTO qt_fmt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_cd) VALUES (20, 10,   'ENG',  'Engineering',    'KR')
    INTO qt_fmt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_cd) VALUES (30, 10,   'OPS',  'Operations',     'US')
    INTO qt_fmt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_cd) VALUES (40, 20,   'DATA', 'Data Platform',  'JP')
    INTO qt_fmt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_cd) VALUES (50, 20,   'APP',  'Applications',   'KR')
SELECT 1
FROM dual;
/

INSERT ALL
    INTO qt_fmt_emp
    (
        emp_id, dept_id, mgr_emp_id, emp_name, login_name, email_addr, salary, bonus_pct,
        hire_dt, status_cd, job_title, note_text, json_doc, xml_doc
    )
    VALUES
    (
        1001, 20, NULL, 'ALICE', 'alice', 'alice@example.com', 120000, 10,
        DATE '2018-03-01', 'ACTIVE', 'Director',
        TO_CLOB('Lead engineer. Special chars: () [] {} ; , /* not comment */ -- not comment'),
        TO_CLOB('{
            "skills": ["sql", "plsql", "java"],
            "meta": {"grade": "A", "remote": true, "tags": ["lead", "mentor"]},
            "history": [{"year": 2023, "score": 91}, {"year": 2024, "score": 95}]
        }'),
        XMLTYPE('<emp><name>ALICE</name><flags><flag>lead</flag><flag>mentor</flag></flags></emp>')
    )
    INTO qt_fmt_emp
    (
        emp_id, dept_id, mgr_emp_id, emp_name, login_name, email_addr, salary, bonus_pct,
        hire_dt, status_cd, job_title, note_text, json_doc, xml_doc
    )
    VALUES
    (
        1002, 40, 1001, 'BOB', 'bob', 'bob@example.com', 90000, 15,
        DATE '2019-06-15', 'ACTIVE', 'Senior Engineer',
        TO_CLOB(q'[Bob's note has quotes: 'single', "double", and q-quote looking text: q'[abc]']'),
        TO_CLOB('{
            "skills": ["oracle", "rust", "fltk"],
            "meta": {"grade": "B", "remote": false, "tags": ["backend", "parser"]},
            "history": [{"year": 2023, "score": 83}, {"year": 2024, "score": 88}]
        }'),
        XMLTYPE('<emp><name>BOB</name><flags><flag>backend</flag><flag>parser</flag></flags></emp>')
    )
    INTO qt_fmt_emp
    (
        emp_id, dept_id, mgr_emp_id, emp_name, login_name, email_addr, salary, bonus_pct,
        hire_dt, status_cd, job_title, note_text, json_doc, xml_doc
    )
    VALUES
    (
        1003, 50, 1001, 'CAROL', 'carol', 'carol@example.com', 87000, 12.5,
        DATE '2020-01-20', 'LEAVE', 'Engineer',
        TO_CLOB('Carol note' || CHR(10) || 'multi-line' || CHR(10) || '(nested (parentheses))'),
        TO_CLOB('{
            "skills": ["ui", "sql", "testing"],
            "meta": {"grade": "A", "remote": true, "tags": ["frontend", "qa"]},
            "history": [{"year": 2023, "score": 90}, {"year": 2024, "score": 92}]
        }'),
        XMLTYPE('<emp><name>CAROL</name><flags><flag>frontend</flag><flag>qa</flag></flags></emp>')
    )
    INTO qt_fmt_emp
    (
        emp_id, dept_id, mgr_emp_id, emp_name, login_name, email_addr, salary, bonus_pct,
        hire_dt, status_cd, job_title, note_text, json_doc, xml_doc
    )
    VALUES
    (
        1004, 30, 1001, 'DAVE', 'dave', 'dave@example.com', 76000, 8,
        DATE '2021-11-05', 'ACTIVE', 'Analyst',
        TO_CLOB('DAVE note with ; semicolon ; and -- dash style'),
        TO_CLOB('{
            "skills": ["ops", "etl"],
            "meta": {"grade": "C", "remote": false, "tags": ["ops"]},
            "history": [{"year": 2023, "score": 72}, {"year": 2024, "score": 75}]
        }'),
        XMLTYPE('<emp><name>DAVE</name><flags><flag>ops</flag></flags></emp>')
    )
SELECT 1
FROM dual;
/

INSERT ALL
    INTO qt_fmt_bonus (emp_id, bonus_year, bonus_type, amount, calc_note) VALUES (1001, 2024, 'BASE',   10000, 'Base bonus')
    INTO qt_fmt_bonus (emp_id, bonus_year, bonus_type, amount, calc_note) VALUES (1001, 2024, 'STOCK',  25000, 'Stock grant')
    INTO qt_fmt_bonus (emp_id, bonus_year, bonus_type, amount, calc_note) VALUES (1002, 2024, 'BASE',    8000, 'Performance adjusted')
    INTO qt_fmt_bonus (emp_id, bonus_year, bonus_type, amount, calc_note) VALUES (1002, 2024, 'SPOT',    1500, 'Special award')
    INTO qt_fmt_bonus (emp_id, bonus_year, bonus_type, amount, calc_note) VALUES (1003, 2024, 'BASE',    6500, 'Leave impact')
    INTO qt_fmt_bonus (emp_id, bonus_year, bonus_type, amount, calc_note) VALUES (1004, 2024, 'BASE',    4000, 'Ops delivery')
SELECT 1
FROM dual;
/

COMMIT;
/

--------------------------------------------------------------------------------
-- VIEW WITH NESTED CTE + JSON_TABLE + XMLTABLE + ANALYTIC + SCALAR SUBQUERY
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW qt_fmt_emp_v
AS
    WITH dept_path
         (
             dept_id,
             parent_dept_id,
             dept_path_txt,
             lvl
         )
         AS
         (
             SELECT d.dept_id,
                    d.parent_dept_id,
                    TO_CHAR(d.dept_name) AS dept_path_txt,
                    1                    AS lvl
             FROM qt_fmt_dept d
             WHERE d.parent_dept_id IS NULL
             UNION ALL
             SELECT c.dept_id,
                    c.parent_dept_id,
                    p.dept_path_txt || ' > ' || c.dept_name,
                    p.lvl + 1
             FROM qt_fmt_dept c
             JOIN dept_path p
               ON p.dept_id = c.parent_dept_id
         ),
         skill_rows
         AS
         (
             SELECT e.emp_id,
                    jt.skill,
                    jt.grade,
                    jt.remote_yn
             FROM qt_fmt_emp e,
                  JSON_TABLE
                  (
                      e.json_doc,
                      '$'
                      COLUMNS
                      (
                          grade      VARCHAR2(10)  PATH '$.meta.grade',
                          remote_yn  VARCHAR2(5)   PATH '$.meta.remote',
                          NESTED PATH '$.skills[*]'
                              COLUMNS
                              (
                                  skill VARCHAR2(100) PATH '$'
                              )
                      )
                  ) jt
         ),
         xml_rows
         AS
         (
             SELECT e.emp_id,
                    x.flag_txt
             FROM qt_fmt_emp e,
                  XMLTABLE
                  (
                      '/emp/flags/flag'
                      PASSING e.xml_doc
                      COLUMNS flag_txt VARCHAR2(100) PATH '.'
                  ) x
         )
    SELECT e.emp_id,
           e.emp_name,
           e.login_name,
           e.email_addr,
           e.salary,
           e.bonus_pct,
           e.hire_dt,
           e.status_cd,
           e.job_title,
           d.dept_id,
           d.dept_code,
           d.dept_name,
           dp.dept_path_txt,
           (
               SELECT LISTAGG(sr.skill, ', ') WITHIN GROUP (ORDER BY sr.skill)
               FROM skill_rows sr
               WHERE sr.emp_id = e.emp_id
           ) AS skill_list,
           (
               SELECT LISTAGG(xr.flag_txt, ', ') WITHIN GROUP (ORDER BY xr.flag_txt)
               FROM xml_rows xr
               WHERE xr.emp_id = e.emp_id
           ) AS flag_list,
           (
               SELECT SUM(b.amount)
               FROM qt_fmt_bonus b
               WHERE b.emp_id = e.emp_id
                 AND b.bonus_year = 2024
           ) AS bonus_2024,
           ROW_NUMBER() OVER
           (
               PARTITION BY e.dept_id
               ORDER BY e.salary DESC NULLS LAST, e.emp_id
           ) AS rn_in_dept,
           DENSE_RANK() OVER
           (
               ORDER BY e.salary DESC NULLS LAST
           ) AS salary_rank_all,
           AVG(e.salary) OVER
           (
               PARTITION BY e.dept_id
           ) AS dept_avg_salary,
           SUM(
               CASE
                   WHEN e.status_cd = 'ACTIVE' THEN NVL(e.salary, 0)
                   ELSE 0
               END
           ) OVER
           (
               PARTITION BY e.dept_id
           ) AS active_salary_sum
    FROM qt_fmt_emp e
    JOIN qt_fmt_dept d
      ON d.dept_id = e.dept_id
    LEFT JOIN dept_path dp
      ON dp.dept_id = d.dept_id;
/

--------------------------------------------------------------------------------
-- PACKAGE WITH:
--   * nested OPEN FOR
--   * dynamic SQL
--   * q-quote
--   * CONNECT BY inside subquery
--   * multilevel CASE / scalar subqueries
--   * collection return
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE qt_fmt_pkg
AS
    FUNCTION get_pairs
    (
        p_emp_id IN NUMBER
    )
        RETURN qt_fmt_pair_tab PIPELINED;

    FUNCTION open_monster_cursor
    (
        p_min_salary IN NUMBER,
        p_region_cd  IN VARCHAR2
    )
        RETURN SYS_REFCURSOR;

    PROCEDURE run_dynamic_merge
    (
        p_bonus_year IN NUMBER
    );
END qt_fmt_pkg;
/

CREATE OR REPLACE PACKAGE BODY qt_fmt_pkg
AS
    FUNCTION get_pairs
    (
        p_emp_id IN NUMBER
    )
        RETURN qt_fmt_pair_tab PIPELINED
    AS
    BEGIN
        FOR r IN
        (
            SELECT 'EMP_ID'   AS k, TO_CHAR(e.emp_id) AS v FROM qt_fmt_emp e WHERE e.emp_id = p_emp_id
            UNION ALL
            SELECT 'EMP_NAME' AS k, e.emp_name        AS v FROM qt_fmt_emp e WHERE e.emp_id = p_emp_id
            UNION ALL
            SELECT 'DEPT'     AS k, d.dept_name       AS v
            FROM qt_fmt_emp e
            JOIN qt_fmt_dept d
              ON d.dept_id = e.dept_id
            WHERE e.emp_id = p_emp_id
        )
        LOOP
            PIPE ROW (qt_fmt_pair_ot(r.k, r.v));
        END LOOP;

        RETURN;
    END get_pairs;

    FUNCTION open_monster_cursor
    (
        p_min_salary IN NUMBER,
        p_region_cd  IN VARCHAR2
    )
        RETURN SYS_REFCURSOR
    AS
        l_rc   SYS_REFCURSOR;
    BEGIN
        OPEN l_rc FOR
            WITH base
                 AS
                 (
                     SELECT /*+ MATERIALIZE */
                            e.emp_id,
                            e.emp_name,
                            e.salary,
                            e.status_cd,
                            e.note_text,
                            e.dept_id,
                            d.dept_name,
                            d.region_cd,
                            (
                                SELECT LISTAGG(p.k || '=' || p.v, '; ') WITHIN GROUP (ORDER BY p.k)
                                FROM TABLE(qt_fmt_pkg.get_pairs(e.emp_id)) p
                            ) AS pair_text,
                            (
                                SELECT MAX(level)
                                FROM
                                (
                                    SELECT level
                                    FROM dual
                                    CONNECT BY level <=
                                               (
                                                   SELECT COUNT(*)
                                                   FROM qt_fmt_bonus b
                                                   WHERE b.emp_id = e.emp_id
                                               )
                                )
                            ) AS bonus_depth,
                            CASE
                                WHEN e.salary >= 100000 THEN
                                    CASE
                                        WHEN e.status_cd = 'ACTIVE' THEN 'HIGH_ACTIVE'
                                        ELSE 'HIGH_NOT_ACTIVE'
                                    END
                                WHEN e.salary BETWEEN 80000 AND 99999.99 THEN
                                    CASE
                                        WHEN e.status_cd = 'ACTIVE' THEN 'MID_ACTIVE'
                                        WHEN e.status_cd = 'LEAVE'  THEN 'MID_LEAVE'
                                        ELSE 'MID_OTHER'
                                    END
                                ELSE
                                    CASE
                                        WHEN EXISTS
                                             (
                                                 SELECT 1
                                                 FROM qt_fmt_bonus bx
                                                 WHERE bx.emp_id = e.emp_id
                                                   AND bx.amount > 5000
                                             ) THEN 'LOW_WITH_BONUS'
                                        ELSE 'LOW'
                                    END
                            END AS band_label
                     FROM qt_fmt_emp e
                     JOIN qt_fmt_dept d
                       ON d.dept_id = e.dept_id
                     WHERE e.salary >= p_min_salary
                       AND d.region_cd = p_region_cd
                 ),
                 enriched
                 AS
                 (
                     SELECT b.*,
                            (
                                SELECT SUM(x.amount)
                                FROM qt_fmt_bonus x
                                WHERE x.emp_id = b.emp_id
                            ) AS bonus_sum,
                            ROW_NUMBER() OVER
                            (
                                PARTITION BY b.dept_id
                                ORDER BY b.salary DESC, b.emp_id
                            ) AS rn
                     FROM base b
                 )
            SELECT e.emp_id,
                   e.emp_name,
                   e.dept_name,
                   e.region_cd,
                   e.salary,
                   e.band_label,
                   e.bonus_sum,
                   e.bonus_depth,
                   e.pair_text,
                   (
                       SELECT JSON_ARRAYAGG(
                                  JSON_OBJECT(
                                      'bonusType' VALUE b.bonus_type,
                                      'amount'    VALUE b.amount
                                  )
                              RETURNING CLOB
                              )
                       FROM qt_fmt_bonus b
                       WHERE b.emp_id = e.emp_id
                   ) AS bonus_json,
                   REGEXP_REPLACE(
                       REPLACE(
                           REPLACE(
                               DBMS_LOB.SUBSTR(e.note_text, 200, 1),
                               CHR(10),
                               ' '
                           ),
                           CHR(13),
                           ' '
                       ),
                       '\s+',
                       ' '
                   ) AS note_preview,
                   CASE
                       WHEN e.rn = 1 THEN q'[TOP_IN_DEPT]'
                       ELSE q'[NOT_TOP_IN_DEPT]'
                   END AS dept_flag
            FROM enriched e
            ORDER BY
                   CASE
                       WHEN e.band_label LIKE 'HIGH%' THEN 1
                       WHEN e.band_label LIKE 'MID%'  THEN 2
                       ELSE 3
                   END,
                   e.salary DESC,
                   e.emp_id;

        RETURN l_rc;
    END open_monster_cursor;

    PROCEDURE run_dynamic_merge
    (
        p_bonus_year IN NUMBER
    )
    AS
        l_sql   CLOB;
    BEGIN
        l_sql :=
               q'[
MERGE INTO qt_fmt_audit t
USING
(
    SELECT e.emp_id,
           e.emp_name,
           d.dept_name,
           (
               SELECT SUM(b.amount)
               FROM qt_fmt_bonus b
               WHERE b.emp_id = e.emp_id
                 AND b.bonus_year = :bonus_year
           ) AS bonus_sum
    FROM qt_fmt_emp e
    JOIN qt_fmt_dept d
      ON d.dept_id = e.dept_id
) s
ON (t.module_name = 'qt_fmt_pkg.run_dynamic_merge' AND t.key_text = TO_CHAR(s.emp_id))
WHEN MATCHED THEN
    UPDATE
       SET t.action_name  = 'UPSERT',
           t.payload_text = 'EMP=' || s.emp_name || ';DEPT=' || s.dept_name || ';BONUS=' || TO_CHAR(NVL(s.bonus_sum, 0)),
           t.created_at   = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT
    (
        module_name,
        action_name,
        key_text,
        payload_text
    )
    VALUES
    (
        'qt_fmt_pkg.run_dynamic_merge',
        'INSERT',
        TO_CHAR(s.emp_id),
        'EMP=' || s.emp_name || ';DEPT=' || s.dept_name || ';BONUS=' || TO_CHAR(NVL(s.bonus_sum, 0))
    )
]';

        EXECUTE IMMEDIATE l_sql USING p_bonus_year;
    END run_dynamic_merge;
END qt_fmt_pkg;
/

--------------------------------------------------------------------------------
-- CALL PACKAGE PROCEDURE
--------------------------------------------------------------------------------
BEGIN
    qt_fmt_pkg.run_dynamic_merge(2024);
END;
/

--------------------------------------------------------------------------------
-- MONSTER QUERY #1
-- nested CTE / scalar subquery / analytic / lateral / json / xml / connect by
--------------------------------------------------------------------------------
WITH
    r
    AS
    (
        SELECT d.dept_id,
               d.parent_dept_id,
               d.dept_name,
               LEVEL AS lvl,
               SYS_CONNECT_BY_PATH(d.dept_name, ' > ') AS path_txt
        FROM qt_fmt_dept d
        START WITH d.parent_dept_id IS NULL
        CONNECT BY PRIOR d.dept_id = d.parent_dept_id
    ),
    ebase
    AS
    (
        SELECT /*+ INLINE */
               e.emp_id,
               e.emp_name,
               e.dept_id,
               e.salary,
               e.status_cd,
               e.job_title,
               e.note_text,
               e.json_doc,
               e.xml_doc,
               COALESCE(e.updated_at, e.created_at) AS last_change_at
        FROM qt_fmt_emp e
        WHERE e.status_cd IN ('ACTIVE', 'LEAVE')
    ),
    ej
    AS
    (
        SELECT e.emp_id,
               jt.grade,
               jt.remote_yn,
               jt.skill
        FROM ebase e,
             JSON_TABLE
             (
                 e.json_doc,
                 '$'
                 COLUMNS
                 (
                     grade      VARCHAR2(10) PATH '$.meta.grade',
                     remote_yn  VARCHAR2(10) PATH '$.meta.remote',
                     NESTED PATH '$.skills[*]'
                         COLUMNS
                         (
                             skill VARCHAR2(100) PATH '$'
                         )
                 )
             ) jt
    ),
    ex
    AS
    (
        SELECT e.emp_id,
               xt.flag_txt
        FROM ebase e,
             XMLTABLE
             (
                 '/emp/flags/flag'
                 PASSING e.xml_doc
                 COLUMNS flag_txt VARCHAR2(100) PATH '.'
             ) xt
    ),
    agg
    AS
    (
        SELECT e.emp_id,
               LISTAGG(DISTINCT j.skill, ', ') WITHIN GROUP (ORDER BY j.skill) AS skill_list,
               LISTAGG(DISTINCT x.flag_txt, ', ') WITHIN GROUP (ORDER BY x.flag_txt) AS flag_list,
               MAX(j.grade) AS grade,
               MAX(j.remote_yn) AS remote_yn
        FROM ebase e
        LEFT JOIN ej j
          ON j.emp_id = e.emp_id
        LEFT JOIN ex x
          ON x.emp_id = e.emp_id
        GROUP BY e.emp_id
    )
SELECT
       q.emp_id,
       q.emp_name,
       q.dept_name,
       q.path_txt,
       q.salary,
       q.skill_list,
       q.flag_list,
       q.grade,
       q.remote_yn,
       q.bonus_sum,
       q.bonus_rank_in_dept,
       q.note_class,
       q.preview_text,
       q.pair_payload,
       q.deep_case_label
FROM
(
    SELECT
           e.emp_id,
           e.emp_name,
           d.dept_name,
           r.path_txt,
           e.salary,
           a.skill_list,
           a.flag_list,
           a.grade,
           a.remote_yn,
           (
               SELECT SUM(b.amount)
               FROM qt_fmt_bonus b
               WHERE b.emp_id = e.emp_id
                 AND b.bonus_year = 2024
           ) AS bonus_sum,
           DENSE_RANK() OVER
           (
               PARTITION BY e.dept_id
               ORDER BY
                   (
                       SELECT SUM(b2.amount)
                       FROM qt_fmt_bonus b2
                       WHERE b2.emp_id = e.emp_id
                   ) DESC NULLS LAST,
                   e.emp_id
           ) AS bonus_rank_in_dept,
           CASE
               WHEN REGEXP_LIKE(DBMS_LOB.SUBSTR(e.note_text, 300, 1), '\(|\)') THEN
                   CASE
                       WHEN REGEXP_LIKE(DBMS_LOB.SUBSTR(e.note_text, 300, 1), 'comment', 'i') THEN 'PAREN_AND_COMMENT_WORD'
                       ELSE 'PAREN_ONLY'
                   END
               WHEN REGEXP_LIKE(DBMS_LOB.SUBSTR(e.note_text, 300, 1), ';') THEN 'SEMICOLON'
               ELSE 'NORMAL'
           END AS note_class,
           REGEXP_REPLACE(
               REPLACE(
                   REPLACE(DBMS_LOB.SUBSTR(e.note_text, 120, 1), CHR(10), ' '),
                   CHR(13),
                   ' '
               ),
               '\s+',
               ' '
           ) AS preview_text,
           (
               SELECT LISTAGG(t.k || ':' || t.v, ' | ') WITHIN GROUP (ORDER BY t.k)
               FROM TABLE(qt_fmt_pkg.get_pairs(e.emp_id)) t
           ) AS pair_payload,
           CASE
               WHEN e.salary >= 100000
                    AND EXISTS
                        (
                            SELECT 1
                            FROM qt_fmt_bonus bx
                            WHERE bx.emp_id = e.emp_id
                              AND bx.amount >= 10000
                        ) THEN
                   CASE
                       WHEN a.grade = 'A' THEN 'ELITE_A'
                       WHEN a.grade = 'B' THEN 'ELITE_B'
                       ELSE 'ELITE_OTHER'
                   END
               WHEN e.salary >= 80000 THEN
                   CASE
                       WHEN a.remote_yn = 'true' THEN 'MID_REMOTE'
                       WHEN a.remote_yn = 'false' THEN 'MID_OFFICE'
                       ELSE 'MID_UNKNOWN'
                   END
               ELSE
                   CASE
                       WHEN EXISTS
                            (
                                SELECT 1
                                FROM qt_fmt_bonus byy
                                WHERE byy.emp_id = e.emp_id
                                  AND byy.bonus_type IN ('SPOT', 'STOCK')
                            ) THEN 'LOW_SPECIAL'
                       ELSE 'LOW_BASIC'
                   END
           END AS deep_case_label
    FROM ebase e
    JOIN qt_fmt_dept d
      ON d.dept_id = e.dept_id
    LEFT JOIN r
      ON r.dept_id = d.dept_id
    LEFT JOIN agg a
      ON a.emp_id = e.emp_id
) q
ORDER BY
       CASE
           WHEN q.deep_case_label LIKE 'ELITE%' THEN 1
           WHEN q.deep_case_label LIKE 'MID%'   THEN 2
           ELSE 3
       END,
       q.bonus_sum DESC NULLS LAST,
       q.emp_id;
/

--------------------------------------------------------------------------------
-- MONSTER QUERY #2
-- PIVOT + UNPIVOT + MODEL + GROUPING SETS
--------------------------------------------------------------------------------
WITH bonus_base
AS
(
    SELECT b.emp_id,
           b.bonus_year,
           b.bonus_type,
           b.amount
    FROM qt_fmt_bonus b
    WHERE b.bonus_year = 2024
),
bonus_pivoted
AS
(
    SELECT *
    FROM bonus_base
    PIVOT
    (
        SUM(amount)
        FOR bonus_type IN
        (
            'BASE'  AS base_amt,
            'SPOT'  AS spot_amt,
            'STOCK' AS stock_amt
        )
    )
),
bonus_unpivoted
AS
(
    SELECT emp_id,
           metric_name,
           metric_value
    FROM bonus_pivoted
    UNPIVOT INCLUDE NULLS
    (
        metric_value
        FOR metric_name IN
        (
            base_amt  AS 'BASE_AMT',
            spot_amt  AS 'SPOT_AMT',
            stock_amt AS 'STOCK_AMT'
        )
    )
),
salary_model
AS
(
    SELECT dept_id,
           emp_id,
           salary,
           0 AS projected_salary
    FROM qt_fmt_emp
    MODEL
        PARTITION BY (dept_id)
        DIMENSION BY (emp_id)
        MEASURES (salary, projected_salary)
        RULES
        (
            projected_salary[ANY] =
                NVL(salary[CV(emp_id)], 0)
                * CASE
                      WHEN NVL(salary[CV(emp_id)], 0) >= 100000 THEN 1.10
                      WHEN NVL(salary[CV(emp_id)], 0) >=  80000 THEN 1.07
                      ELSE 1.03
                  END
        )
)
SELECT
       COALESCE(TO_CHAR(e.dept_id), 'ALL_DEPT') AS dept_id_txt,
       COALESCE(e.status_cd, 'ALL_STATUS')      AS status_cd,
       SUM(e.salary)                            AS total_salary,
       AVG(sm.projected_salary)                 AS avg_projected_salary,
       MAX(CASE WHEN bu.metric_name = 'BASE_AMT'  THEN bu.metric_value END) AS max_base_amt,
       MAX(CASE WHEN bu.metric_name = 'SPOT_AMT'  THEN bu.metric_value END) AS max_spot_amt,
       MAX(CASE WHEN bu.metric_name = 'STOCK_AMT' THEN bu.metric_value END) AS max_stock_amt
FROM qt_fmt_emp e
LEFT JOIN salary_model sm
  ON sm.emp_id = e.emp_id
LEFT JOIN bonus_unpivoted bu
  ON bu.emp_id = e.emp_id
GROUP BY GROUPING SETS
(
    (e.dept_id, e.status_cd),
    (e.dept_id),
    (e.status_cd),
    ()
)
ORDER BY
       dept_id_txt,
       status_cd;
/

--------------------------------------------------------------------------------
-- MONSTER QUERY #3
-- CROSS APPLY / OUTER APPLY style stress (Oracle supports LATERAL)
--------------------------------------------------------------------------------
SELECT
       e.emp_id,
       e.emp_name,
       x.top_bonus_type,
       x.top_bonus_amt,
       y.skill_cnt,
       y.first_skill
FROM qt_fmt_emp e
     OUTER APPLY
     (
         SELECT b.bonus_type AS top_bonus_type,
                b.amount     AS top_bonus_amt
         FROM qt_fmt_bonus b
         WHERE b.emp_id = e.emp_id
         ORDER BY b.amount DESC NULLS LAST, b.bonus_type
         FETCH FIRST 1 ROW ONLY
     ) x
     OUTER APPLY
     (
         SELECT COUNT(*)      AS skill_cnt,
                MIN(jt.skill) AS first_skill
         FROM JSON_TABLE
              (
                  e.json_doc,
                  '$.skills[*]'
                  COLUMNS
                  (
                      skill VARCHAR2(100) PATH '$'
                  )
              ) jt
     ) y
ORDER BY e.emp_id;
/

--------------------------------------------------------------------------------
-- MERGE STRESS
--------------------------------------------------------------------------------
MERGE INTO qt_fmt_bonus t
USING
(
    SELECT e.emp_id,
           2025 AS bonus_year,
           CASE
               WHEN e.salary >= 100000 THEN 'BASE'
               WHEN e.salary >=  80000 THEN 'SPOT'
               ELSE 'BASE'
           END AS bonus_type,
           ROUND(
               NVL(e.salary, 0)
               * CASE
                     WHEN e.status_cd = 'ACTIVE' THEN 0.05
                     ELSE 0.02
                 END,
               2
           ) AS amount,
           'generated by merge' AS calc_note
    FROM qt_fmt_emp e
) s
ON
(
       t.emp_id      = s.emp_id
   AND t.bonus_year  = s.bonus_year
   AND t.bonus_type  = s.bonus_type
)
WHEN MATCHED THEN
    UPDATE
       SET t.amount    = s.amount,
           t.calc_note = s.calc_note || ' / updated'
WHEN NOT MATCHED THEN
    INSERT
    (
        emp_id,
        bonus_year,
        bonus_type,
        amount,
        calc_note
    )
    VALUES
    (
        s.emp_id,
        s.bonus_year,
        s.bonus_type,
        s.amount,
        s.calc_note
    );
/

--------------------------------------------------------------------------------
-- MULTI-TABLE INSERT STRESS
--------------------------------------------------------------------------------
INSERT ALL
    WHEN salary >= 100000 THEN
        INTO qt_fmt_audit (module_name, action_name, key_text, payload_text)
        VALUES ('HIGH_SALARY', 'INSERT_ALL', TO_CHAR(emp_id), 'salary=' || TO_CHAR(salary))
    WHEN status_cd = 'LEAVE' THEN
        INTO qt_fmt_audit (module_name, action_name, key_text, payload_text)
        VALUES ('LEAVE_STATUS', 'INSERT_ALL', TO_CHAR(emp_id), 'name=' || emp_name)
    ELSE
        INTO qt_fmt_audit (module_name, action_name, key_text, payload_text)
        VALUES ('OTHER_EMP', 'INSERT_ALL', TO_CHAR(emp_id), 'dept=' || TO_CHAR(dept_id))
SELECT e.emp_id,
       e.emp_name,
       e.salary,
       e.status_cd,
       e.dept_id
FROM qt_fmt_emp e;
/

--------------------------------------------------------------------------------
-- UPDATE WITH SCALAR SUBQUERY + CASE + EXISTS
--------------------------------------------------------------------------------
UPDATE qt_fmt_emp e
   SET e.updated_at =
       CASE
           WHEN EXISTS
                (
                    SELECT 1
                    FROM qt_fmt_bonus b
                    WHERE b.emp_id = e.emp_id
                      AND b.amount >
                          (
                              SELECT AVG(b2.amount)
                              FROM qt_fmt_bonus b2
                              WHERE b2.bonus_year = b.bonus_year
                          )
                ) THEN SYSTIMESTAMP
           ELSE NVL(e.updated_at, SYSTIMESTAMP)
       END,
       e.job_title =
       CASE
           WHEN e.job_title LIKE '%Engineer%' AND e.status_cd = 'ACTIVE' THEN e.job_title || ' / Core'
           WHEN e.status_cd = 'LEAVE' THEN e.job_title || ' / On Leave'
           ELSE e.job_title
       END
 WHERE e.emp_id IN
       (
           SELECT ev.emp_id
           FROM qt_fmt_emp_v ev
           WHERE ev.salary_rank_all <= 4
       );
/

--------------------------------------------------------------------------------
-- DELETE WITH NESTED IN / EXISTS / GROUP BY HAVING
--------------------------------------------------------------------------------
DELETE FROM qt_fmt_audit a
WHERE a.audit_id IN
(
    SELECT x.audit_id
    FROM qt_fmt_audit x
    WHERE EXISTS
          (
              SELECT 1
              FROM
              (
                  SELECT key_text,
                         COUNT(*) AS cnt
                  FROM qt_fmt_audit g
                  GROUP BY key_text
                  HAVING COUNT(*) > 3
              ) z
              WHERE z.key_text = x.key_text
          )
      AND x.module_name IN ('OTHER_EMP')
);
/

--------------------------------------------------------------------------------
-- REF CURSOR OPEN TEST BLOCK
--------------------------------------------------------------------------------
DECLARE
    l_rc             SYS_REFCURSOR;
    l_emp_id         qt_fmt_emp.emp_id%TYPE;
    l_emp_name       qt_fmt_emp.emp_name%TYPE;
    l_dept_name      qt_fmt_dept.dept_name%TYPE;
    l_region_cd      qt_fmt_dept.region_cd%TYPE;
    l_salary         qt_fmt_emp.salary%TYPE;
    l_band_label     VARCHAR2(100);
    l_bonus_sum      NUMBER;
    l_bonus_depth    NUMBER;
    l_pair_text      VARCHAR2(4000);
    l_bonus_json     CLOB;
    l_note_preview   VARCHAR2(4000);
    l_dept_flag      VARCHAR2(100);
BEGIN
    l_rc := qt_fmt_pkg.open_monster_cursor(70000, 'KR');

    LOOP
        FETCH l_rc
            INTO l_emp_id,
                 l_emp_name,
                 l_dept_name,
                 l_region_cd,
                 l_salary,
                 l_band_label,
                 l_bonus_sum,
                 l_bonus_depth,
                 l_pair_text,
                 l_bonus_json,
                 l_note_preview,
                 l_dept_flag;

        EXIT WHEN l_rc%NOTFOUND;

        INSERT INTO qt_fmt_audit
        (
            module_name,
            action_name,
            key_text,
            payload_text
        )
        VALUES
        (
            'REF_CURSOR_LOOP',
            'FETCH',
            TO_CHAR(l_emp_id),
            'EMP=' || l_emp_name
            || ';DEPT=' || l_dept_name
            || ';REGION=' || l_region_cd
            || ';SAL=' || TO_CHAR(l_salary)
            || ';BAND=' || l_band_label
            || ';BONUS=' || TO_CHAR(NVL(l_bonus_sum, 0))
            || ';DEPTH=' || TO_CHAR(NVL(l_bonus_depth, 0))
            || ';FLAG=' || l_dept_flag
            || ';PAIR=' || SUBSTR(l_pair_text, 1, 500)
            || ';NOTE=' || SUBSTR(l_note_preview, 1, 200)
        );
    END LOOP;

    CLOSE l_rc;
END;
/

--------------------------------------------------------------------------------
-- DYNAMIC SQL + nested parentheses + quoted literals + operator wrapping
--------------------------------------------------------------------------------
DECLARE
    l_sql      CLOB;
    l_cnt      NUMBER;
    l_region   VARCHAR2(10) := 'KR';
BEGIN
    l_sql :=
           'SELECT COUNT(*) '
        || 'FROM ( '
        || '    SELECT e.emp_id '
        || '    FROM qt_fmt_emp e '
        || '    JOIN qt_fmt_dept d '
        || '      ON d.dept_id = e.dept_id '
        || '    WHERE ( ( e.status_cd = ''ACTIVE'' ) OR ( e.status_cd = ''LEAVE'' ) ) '
        || '      AND ( d.region_cd = :x ) '
        || '      AND ( NVL(e.salary, 0) + NVL((SELECT SUM(b.amount) '
        || '                                  FROM qt_fmt_bonus b '
        || '                                  WHERE b.emp_id = e.emp_id), 0) ) >= 80000 '
        || ') z';

    EXECUTE IMMEDIATE l_sql
        INTO l_cnt
        USING l_region;

    INSERT INTO qt_fmt_audit
    (
        module_name,
        action_name,
        key_text,
        payload_text
    )
    VALUES
    (
        'DYNAMIC_SQL',
        'COUNT',
        'KR_80000_PLUS',
        'CNT=' || TO_CHAR(l_cnt)
    );
END;
/

--------------------------------------------------------------------------------
-- HINTS + COMMENTS + weird line breaks test
--------------------------------------------------------------------------------
SELECT /*+ LEADING(e d) USE_HASH(d) */
       e.emp_id,                         -- inline comment after column
       e.emp_name,
       d.dept_name,
       /* block comment with tokens:
          SELECT FROM WHERE CASE END CONNECT BY START WITH
          Formatter must not treat this as real SQL.
       */
       CASE
           WHEN e.salary > 100000 THEN 'A'
           WHEN e.salary >  80000 THEN 'B'
           ELSE 'C'
       END AS grade_cd
FROM qt_fmt_emp e
JOIN qt_fmt_dept d
  ON d.dept_id = e.dept_id
WHERE
        (
            e.status_cd = 'ACTIVE'
            AND
            (
                d.region_cd = 'KR'
                OR d.region_cd = 'JP'
            )
        )
     OR (
            e.status_cd = 'LEAVE'
            AND e.emp_id IN
                (
                    SELECT b.emp_id
                    FROM qt_fmt_bonus b
                    WHERE b.amount > 5000
                )
        )
ORDER BY
       grade_cd,
       e.emp_id;
/

--------------------------------------------------------------------------------
-- FINAL MONSTER SELECT AGAINST VIEW
-- formatter killer: nested scalar subquery, TABLE(), CASE, LISTAGG, EXISTS
--------------------------------------------------------------------------------
SELECT
       v.emp_id,
       v.emp_name,
       v.dept_name,
       v.dept_path_txt,
       v.salary,
       v.skill_list,
       v.flag_list,
       (
           SELECT MIN(p.v)
           FROM TABLE(qt_fmt_pkg.get_pairs(v.emp_id)) p
           WHERE p.k = 'EMP_NAME'
       ) AS min_pair_value,
       CASE
           WHEN EXISTS
                (
                    SELECT 1
                    FROM qt_fmt_bonus b
                    WHERE b.emp_id = v.emp_id
                      AND b.bonus_year IN
                          (
                              SELECT y.column_value
                              FROM TABLE(sys.odcinumberlist(2024, 2025)) y
                          )
                ) THEN
               (
                   SELECT LISTAGG(b2.bonus_type || ':' || TO_CHAR(b2.amount), ', ')
                          WITHIN GROUP (ORDER BY b2.bonus_year, b2.bonus_type)
                   FROM qt_fmt_bonus b2
                   WHERE b2.emp_id = v.emp_id
               )
           ELSE 'NO_BONUS'
       END AS bonus_detail_txt,
       CASE
           WHEN v.rn_in_dept = 1 THEN 'TOP'
           WHEN v.rn_in_dept = 2 THEN 'SECOND'
           ELSE 'OTHER'
       END AS dept_rank_label
FROM qt_fmt_emp_v v
WHERE v.emp_id IN (1001, 1002, 1003, 1004)
ORDER BY
       CASE
           WHEN v.salary_rank_all = 1 THEN 1
           WHEN v.salary_rank_all = 2 THEN 2
           ELSE 3
       END,
       v.emp_id;
/

COMMIT;
/

--------------------------------------------------------------------------------
-- OPTIONAL CHECK
-- 이 SELECT는 formatter 결과물 최종 육안 점검용
--------------------------------------------------------------------------------
SELECT
       a.audit_id,
       a.module_name,
       a.action_name,
       a.key_text,
       SUBSTR(a.payload_text, 1, 200) AS payload_preview,
       a.created_at
FROM qt_fmt_audit a
ORDER BY a.audit_id;
