--------------------------------------------------------------------------------
-- EXTREME ORACLE PARSER / FORMATTER VALIDATION SCRIPT
-- 목적:
--   1) 실행단위 분리
--   2) 중첩 구조 파싱
--   3) 자동 포매팅 안정성
--   4) SQL + PL/SQL 혼합 처리 검증
--
-- 주의:
--   - SYS/SYSTEM이 아닌 일반 테스트 스키마에서 실행 권장
--   - 여러 번 재실행 가능하도록 DROP 예외 처리 포함
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- CLEANUP
--------------------------------------------------------------------------------

BEGIN
    FOR r IN (
        SELECT object_name,
            object_type
        FROM user_objects
        WHERE object_name IN ('QT_EMP', 'QT_DEPT', 'QT_SALES', 'QT_AUDIT_LOG', 'QT_EMP_BIUD', 'QT_EMP_SUMMARY_V', 'QT_PKG_EXTREME', 'QT_SEQ_EMP', 'QT_SEQ_SALES')
    ) LOOP
        BEGIN
            IF r.object_type = 'TABLE' THEN
                EXECUTE IMMEDIATE 'DROP TABLE ' || r.object_name || ' CASCADE CONSTRAINTS PURGE';
            ELSIF r.object_type = 'VIEW' THEN
                EXECUTE IMMEDIATE 'DROP VIEW ' || r.object_name;
            ELSIF r.object_type = 'PACKAGE' THEN
                EXECUTE IMMEDIATE 'DROP PACKAGE ' || r.object_name;
            ELSIF r.object_type = 'TRIGGER' THEN
                EXECUTE IMMEDIATE 'DROP TRIGGER ' || r.object_name;
            ELSIF r.object_type = 'SEQUENCE' THEN
                EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.object_name;
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;
    END LOOP;
END;
/

--------------------------------------------------------------------------------
-- SEQUENCES
--------------------------------------------------------------------------------

CREATE SEQUENCE qt_seq_emp
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

CREATE SEQUENCE qt_seq_sales
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

--------------------------------------------------------------------------------
-- TABLES
--------------------------------------------------------------------------------

CREATE TABLE qt_dept (
    dept_id        NUMBER        CONSTRAINT qt_dept_pk PRIMARY KEY,
    parent_dept_id NUMBER        NULL,
    dept_code      VARCHAR2(30)  NOT NULL,
    dept_name      VARCHAR2(100) NOT NULL,
    region_name    VARCHAR2(50),
    created_at     DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT qt_dept_uk UNIQUE(dept_code),
    CONSTRAINT qt_dept_parent_fk FOREIGN KEY(parent_dept_id) REFERENCES qt_dept(dept_id)
);
/

CREATE TABLE qt_emp (
    emp_id      NUMBER        CONSTRAINT qt_emp_pk PRIMARY KEY,
    dept_id     NUMBER        NOT NULL,
    mgr_emp_id  NUMBER        NULL,
    emp_no      VARCHAR2(30)  NOT NULL,
    emp_name    VARCHAR2(100) NOT NULL,
    job_title   VARCHAR2(100),
    salary      NUMBER(15, 2),
    bonus       NUMBER(15, 2),
    hire_date   DATE,
    status_code VARCHAR2(20),
    email       VARCHAR2(200),
    remarks     CLOB,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT qt_emp_uk UNIQUE(emp_no),
    CONSTRAINT qt_emp_dept_fk FOREIGN KEY(dept_id) REFERENCES qt_dept(dept_id),
    CONSTRAINT qt_emp_mgr_fk FOREIGN KEY(mgr_emp_id) REFERENCES qt_emp(emp_id),
    CONSTRAINT qt_emp_salary_ck CHECK(salary IS NULL OR salary >= 0),
    CONSTRAINT qt_emp_status_ck CHECK(status_code IN('ACTIVE', 'INACTIVE', 'LEAVE'))
);
/

CREATE TABLE qt_sales (
    sale_id      NUMBER        CONSTRAINT qt_sales_pk PRIMARY KEY,
    emp_id       NUMBER        NOT NULL,
    dept_id      NUMBER        NOT NULL,
    sale_year    NUMBER(4)     NOT NULL,
    sale_month   NUMBER(2)     NOT NULL,
    sale_amount  NUMBER(15, 2) NOT NULL,
    sale_type    VARCHAR2(30),
    channel_code VARCHAR2(30),
    created_at   DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT qt_sales_emp_fk FOREIGN KEY(emp_id) REFERENCES qt_emp(emp_id),
    CONSTRAINT qt_sales_dept_fk FOREIGN KEY(dept_id) REFERENCES qt_dept(dept_id),
    CONSTRAINT qt_sales_ck_month CHECK(sale_month BETWEEN 1 AND 12)
);
/

CREATE TABLE qt_audit_log (
    log_id       NUMBER         GENERATED BY DEFAULT AS IDENTITY,
    log_time     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    log_level    VARCHAR2(20),
    module_name  VARCHAR2(100),
    message_text VARCHAR2(4000),
    extra_text   CLOB,
    CONSTRAINT qt_audit_log_pk PRIMARY KEY(log_id)
);
/

--------------------------------------------------------------------------------
-- SEED DATA
--------------------------------------------------------------------------------

INSERT INTO qt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_name)
VALUES (10, NULL, 'HQ', 'Headquarters', 'GLOBAL');

INSERT INTO qt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_name)
VALUES (20, 10, 'ENG', 'Engineering', 'APAC');

INSERT INTO qt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_name)
VALUES (30, 10, 'SAL', 'Sales', 'EMEA');

INSERT INTO qt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_name)
VALUES (40, 20, 'PLT', 'Platform', 'APAC');

INSERT INTO qt_dept (dept_id, parent_dept_id, dept_code, dept_name, region_name)
VALUES (50, 20, 'APP', 'Applications', 'NA');

INSERT INTO qt_emp (emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title, salary, bonus, hire_date, status_code, email, remarks, updated_at)
VALUES (qt_seq_emp.NEXTVAL, 10, NULL, 'E0001', 'ALICE', 'CEO', 250000, 50000, DATE '2015-01-05', 'ACTIVE', 'alice@example.com', TO_CLOB ('Top executive'), SYSTIMESTAMP);

INSERT INTO qt_emp (emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title, salary, bonus, hire_date, status_code, email, remarks, updated_at)
VALUES (qt_seq_emp.NEXTVAL, 20, 1, 'E0002', 'BOB', 'VP ENGINEERING', 180000, 30000, DATE '2016-03-15', 'ACTIVE', 'bob@example.com', TO_CLOB ('Leads engineering'), SYSTIMESTAMP);

INSERT INTO qt_emp (emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title, salary, bonus, hire_date, status_code, email, remarks, updated_at)
VALUES (qt_seq_emp.NEXTVAL, 30, 1, 'E0003', 'CAROL', 'VP SALES', 175000, 40000, DATE '2017-06-20', 'ACTIVE', 'carol@example.com', TO_CLOB ('Leads sales'), SYSTIMESTAMP);

INSERT INTO qt_emp (emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title, salary, bonus, hire_date, status_code, email, remarks, updated_at)
VALUES (qt_seq_emp.NEXTVAL, 40, 2, 'E0004', 'DAVE', 'PLATFORM LEAD', 145000, 15000, DATE '2018-08-01', 'ACTIVE', 'dave@example.com', TO_CLOB ('Platform org'), SYSTIMESTAMP);

INSERT INTO qt_emp (emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title, salary, bonus, hire_date, status_code, email, remarks, updated_at)
VALUES (qt_seq_emp.NEXTVAL, 50, 2, 'E0005', 'ERIN', 'APP LEAD', 142000, 12000, DATE '2019-02-10', 'LEAVE', 'erin@example.com', TO_CLOB ('Applications org'), SYSTIMESTAMP);

INSERT INTO qt_emp (emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title, salary, bonus, hire_date, status_code, email, remarks, updated_at)
VALUES (qt_seq_emp.NEXTVAL, 30, 3, 'E0006', 'FRANK', 'ACCOUNT EXECUTIVE', 98000, 35000, DATE '2020-11-11', 'ACTIVE', 'frank@example.com', TO_CLOB ('Enterprise sales'), SYSTIMESTAMP);

INSERT INTO qt_sales
SELECT qt_seq_sales.NEXTVAL,
    e.emp_id,
    e.dept_id,
    y.sale_year,
    m.sale_month,
    ROUND (
        CASE
            WHEN e.dept_id = 30 THEN DBMS_RANDOM.VALUE (10000, 60000)
            WHEN e.dept_id IN (40, 50) THEN DBMS_RANDOM.VALUE (3000, 15000)
            ELSE DBMS_RANDOM.VALUE (1000, 5000)
        END, 2) AS sale_amount,
    CASE MOD (m.sale_month, 3)
        WHEN 0 THEN 'SUBSCRIPTION'
        WHEN 1 THEN 'LICENSE'
        ELSE 'SERVICE'
    END AS sale_type,
    CASE MOD (m.sale_month, 2)
        WHEN 0 THEN 'ONLINE'
        ELSE 'DIRECT'
    END AS channel_code,
    ADD_MONTHS (DATE '2023-01-01', m.sale_month - 1)
FROM qt_emp e
CROSS JOIN (
        SELECT 2023 AS sale_year
        FROM DUAL
        UNION ALL
        SELECT 2024 AS sale_year
        FROM DUAL
    ) y
CROSS JOIN (
        SELECT LEVEL AS sale_month
        FROM DUAL
        CONNECT BY LEVEL <= 12
    ) m
WHERE e.status_code IN ('ACTIVE', 'LEAVE');
/

COMMIT;
/

--------------------------------------------------------------------------------
-- TRIGGER
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER qt_emp_biud
    BEFORE INSERT OR UPDATE ON qt_emp
    FOR EACH ROW
DECLARE
    v_msg VARCHAR2 (4000);
BEGIN
    IF INSERTING THEN
        IF :NEW.emp_id IS
                NULL THEN
                :NEW.emp_id := qt_seq_emp.NEXTVAL;
        END IF;
            :NEW.created_at := SYSTIMESTAMP;
            v_msg := 'INSERT emp_no=' || :NEW.emp_no || ', dept_id=' || :NEW.dept_id;
    ELSIF UPDATING THEN
            :NEW.updated_at := SYSTIMESTAMP;
            v_msg := 'UPDATE emp_no=' || :OLD.emp_no || ' -> ' || :NEW.emp_no;
    END IF;
        INSERT INTO qt_audit_log (log_level, module_name, message_text, extra_text)
        VALUES ('INFO', 'qt_emp_biud', v_msg, TO_CLOB ('row-level trigger fired'));
END;
/

SHOW ERRORS

--------------------------------------------------------------------------------
-- VIEW WITH AGGREGATION + ANALYTIC + SUBQUERY
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW qt_emp_summary_v AS
WITH base_sales AS (
    SELECT
        s.emp_id,
        s.dept_id,
        s.sale_year,
        s.sale_month,
        s.sale_amount,
        SUM (s.sale_amount) OVER (PARTITION BY s.emp_id, s.sale_year ORDER BY s.sale_month) AS running_amt,
        AVG (s.sale_amount) OVER (PARTITION BY s.emp_id, s.sale_year) AS avg_amt
    FROM qt_sales s
),
yearly_sales AS (
    SELECT
        emp_id,
        dept_id,
        sale_year,
        SUM (sale_amount) AS total_amt,
        MAX (running_amt) AS final_running_amt,
        MAX (avg_amt) AS avg_amt
    FROM base_sales
    GROUP BY emp_id,
        dept_id,
        sale_year
)
SELECT
    e.emp_id,
    e.emp_no,
    e.emp_name,
    e.job_title,
    e.status_code,
    d.dept_code,
    d.dept_name,
    y.sale_year,
    y.total_amt,
    y.final_running_amt,
    y.avg_amt,
    DENSE_RANK () OVER (PARTITION BY y.sale_year ORDER BY y.total_amt DESC NULLS LAST) AS sales_rank,
    (
        SELECT COUNT (*)
        FROM qt_emp x
        WHERE x.mgr_emp_id = e.emp_id
    ) AS direct_report_cnt
FROM qt_emp e
JOIN qt_dept d
    ON d.dept_id = e.dept_id
LEFT JOIN yearly_sales y
    ON y.emp_id = e.emp_id;
/

--------------------------------------------------------------------------------
-- PACKAGE SPEC
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE qt_pkg_extreme IS
    TYPE t_num_tab IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    TYPE t_emp_rec IS RECORD (emp_id qt_emp.emp_id%TYPE, emp_no qt_emp.emp_no%TYPE, emp_name qt_emp.emp_name%TYPE, salary qt_emp.salary%TYPE);
    TYPE t_emp_tab IS TABLE OF t_emp_rec INDEX BY PLS_INTEGER;
    g_default_raise_pct CONSTANT NUMBER := 0.07;
    PROCEDURE seed_extra_rows (p_count NUMBER DEFAULT 5);
    FUNCTION calc_comp_ratio (p_emp_id IN NUMBER, p_target_salary IN NUMBER DEFAULT 150000) RETURN NUMBER;
    FUNCTION get_emp_cursor (p_dept_id IN NUMBER, p_status_code IN VARCHAR2 DEFAULT 'ACTIVE') RETURN SYS_REFCURSOR;
    PROCEDURE adjust_salary (p_dept_id IN NUMBER, p_raise_pct IN NUMBER DEFAULT g_default_raise_pct, p_commit IN BOOLEAN DEFAULT FALSE);
    PROCEDURE write_log (p_level IN VARCHAR2, p_module IN VARCHAR2, p_message IN VARCHAR2, p_extra IN CLOB DEFAULT NULL);
    PROCEDURE run_all;
END qt_pkg_extreme;
/

SHOW ERRORS

--------------------------------------------------------------------------------
-- PACKAGE BODY
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY qt_pkg_extreme IS
    ----------------------------------------------------------------------------
    -- autonomous logger
    ----------------------------------------------------------------------------
    PROCEDURE write_log (p_level IN VARCHAR2, p_module IN VARCHAR2, p_message IN VARCHAR2, p_extra IN CLOB DEFAULT NULL) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO qt_audit_log (log_level, module_name, message_text, extra_text)
        VALUES (p_level, p_module, SUBSTR (p_message, 1, 4000), p_extra);
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
    END write_log;

    ----------------------------------------------------------------------------
    -- add synthetic employees using dynamic SQL + q-quote
    ----------------------------------------------------------------------------
    PROCEDURE seed_extra_rows (p_count NUMBER DEFAULT 5) IS
        v_sql CLOB;
        v_emp_no VARCHAR2 (30);
        v_idx PLS_INTEGER;
    BEGIN
        v_sql := q'[
            INSERT INTO qt_emp
            (
                emp_id, dept_id, mgr_emp_id, emp_no, emp_name, job_title,
                salary, bonus, hire_date, status_code, email, remarks, updated_at
            )
            VALUES
            (
                :1, :2, :3, :4, :5, :6,
                :7, :8, :9, :10, :11, :12, SYSTIMESTAMP
            )
        ]';
        v_idx := 1;
        <<seed_loop>>
        WHILE v_idx <= NVL (p_count, 0) LOOP
            v_emp_no := 'E9' || LPAD (v_idx, 3, '0');
            EXECUTE IMMEDIATE v_sql
            USING qt_seq_emp.NEXTVAL,
            CASE MOD (v_idx, 3)
                WHEN 0 THEN
                    30
                WHEN 1 THEN
                    40
                ELSE
                    50
            END,
            CASE
                WHEN MOD (v_idx, 3) = 0 THEN
                    3
                ELSE
                    2
            END,
                v_emp_no,
                'TEMP_' || v_idx,
            CASE
                WHEN MOD (v_idx, 2) = 0 THEN
                    'CONTRACTOR'
                ELSE
                    'ANALYST'
            END,
                ROUND (DBMS_RANDOM.VALUE (70000, 120000), 2),
                ROUND (DBMS_RANDOM.VALUE (0, 10000), 2),
                ADD_MONTHS (TRUNC (SYSDATE), - v_idx),
            CASE
                WHEN MOD (v_idx, 5) = 0 THEN
                    'LEAVE'
                ELSE
                    'ACTIVE'
            END,
                LOWER (v_emp_no) || '@example.com',
                TO_CLOB ('Synthetic row generated by seed_extra_rows #' || v_idx);
            v_idx := v_idx + 1;
        END LOOP seed_loop;
        write_log ('INFO', 'seed_extra_rows', 'Inserted rows=' || p_count);
    END seed_extra_rows;

    ----------------------------------------------------------------------------
    -- scalar function with nested queries + CASE + NULLIF
    ----------------------------------------------------------------------------
    FUNCTION calc_comp_ratio (p_emp_id IN NUMBER, p_target_salary IN NUMBER DEFAULT 150000) RETURN NUMBER IS
        v_salary NUMBER;
        v_ratio NUMBER;
    BEGIN
        SELECT e.salary
        INTO v_salary
        FROM qt_emp e
        WHERE e.emp_id = p_emp_id;
        v_ratio :=
        CASE
            WHEN p_target_salary IS NULL
                OR p_target_salary = 0 THEN
                NULL
            WHEN v_salary IS NULL THEN
                0
            ELSE
                ROUND (v_salary / NULLIF (p_target_salary, 0), 6)
        END;
        RETURN v_ratio;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            write_log ('WARN', 'calc_comp_ratio', 'No employee found. emp_id=' || p_emp_id);
            RETURN NULL;
        WHEN OTHERS THEN
            write_log ('ERROR', 'calc_comp_ratio', SQLERRM, TO_CLOB (DBMS_UTILITY.FORMAT_ERROR_BACKTRACE));
            RAISE;
    END calc_comp_ratio;

    ----------------------------------------------------------------------------
    -- ref cursor with nested inline view + correlated subquery + analytics
    ----------------------------------------------------------------------------
    FUNCTION get_emp_cursor (p_dept_id IN NUMBER, p_status_code IN VARCHAR2 DEFAULT 'ACTIVE') RETURN SYS_REFCURSOR IS
        v_rc SYS_REFCURSOR;
    BEGIN
        OPEN v_rc FOR
            SELECT *
            FROM (
                SELECT e.emp_id,
                    e.emp_no,
                    e.emp_name,
                    e.job_title,
                    e.salary,
                    e.bonus,
                    d.dept_name,
                    (
                    SELECT NVL (SUM (s.sale_amount), 0)
                    FROM qt_sales s
                    WHERE s.emp_id = e.emp_id
                        AND s.sale_year = EXTRACT (YEAR
                    FROM SYSDATE)
                ) AS current_year_sales,
                    ROW_NUMBER () OVER (ORDER BY e.salary DESC NULLS LAST, e.emp_id) AS rn,
                    COUNT (*) OVER () AS total_cnt
                FROM qt_emp e
                    JOIN qt_dept d
                    ON d.dept_id = e.dept_id
                WHERE e.dept_id = p_dept_id
                    AND e.status_code = NVL (p_status_code, e.status_code)
            )
            WHERE rn <= 100
            ORDER BY rn;
        RETURN v_rc;
    END get_emp_cursor;

    ----------------------------------------------------------------------------
    -- bulk collect + forall + save exceptions + nested blocks
    ----------------------------------------------------------------------------
    PROCEDURE adjust_salary (p_dept_id IN NUMBER, p_raise_pct IN NUMBER DEFAULT g_default_raise_pct, p_commit IN BOOLEAN DEFAULT FALSE) IS
        TYPE t_emp_id_tab IS TABLE OF qt_emp.emp_id%TYPE INDEX BY PLS_INTEGER;
        v_emp_ids t_emp_id_tab;
        v_count PLS_INTEGER := 0;
        v_effective_pct NUMBER;
        e_bulk_errors EXCEPTION;
        PRAGMA EXCEPTION_INIT (e_bulk_errors, - 24381);
    BEGIN
        v_effective_pct :=
        CASE
            WHEN p_raise_pct IS NULL THEN
                g_default_raise_pct
            WHEN p_raise_pct < - 0.50 THEN
                - 0.50
            WHEN p_raise_pct > 1.00 THEN
                1.00
            ELSE
                p_raise_pct
        END;
        SELECT emp_id BULK COLLECT
        INTO v_emp_ids
        FROM qt_emp
        WHERE dept_id = p_dept_id
            AND status_code = 'ACTIVE'
            AND NVL (salary, 0) > 0
        ORDER BY emp_id;
        v_count := v_emp_ids.COUNT;
        IF v_count = 0 THEN
            write_log ('INFO', 'adjust_salary', 'No active employees for dept_id=' || p_dept_id);
            RETURN;
        END IF;
        BEGIN
            FORALL i IN INDICES OF v_emp_ids SAVE EXCEPTIONS
            UPDATE qt_emp
            SET salary = ROUND (salary * (
                    CASE
                        WHEN salary < 100000 THEN
                    1 + v_effective_pct + 0.01
                        WHEN salary BETWEEN 100000 AND 150000 THEN
                    1 + v_effective_pct
                        ELSE
                    1 + v_effective_pct - 0.005
                    END
                ), 2),
                bonus = ROUND (NVL (bonus, 0) +
                    CASE
                        WHEN dept_id = 30 THEN
                    3000
                        WHEN dept_id IN (40, 50) THEN
                    1500
                        ELSE
                    800
                    END, 2),
                updated_at = SYSTIMESTAMP
            WHERE emp_id = v_emp_ids (i);
        EXCEPTION
            WHEN e_bulk_errors THEN
                FOR j IN 1..SQL%BULK_EXCEPTIONS.COUNT LOOP
                    write_log ('ERROR', 'adjust_salary', 'Bulk exception idx=' || SQL%BULK_EXCEPTIONS (j).ERROR_INDEX || ', code=' || SQL%BULK_EXCEPTIONS (j).ERROR_CODE);
                END LOOP;
                RAISE;
        END;
        IF p_commit THEN
            COMMIT;
        END IF;
        write_log ('INFO', 'adjust_salary', 'Adjusted dept_id=' || p_dept_id || ', count=' || v_count || ', pct=' || v_effective_pct);
    EXCEPTION
        WHEN OTHERS THEN
            IF p_commit THEN
                ROLLBACK;
            END IF;
            write_log ('ERROR', 'adjust_salary', SQLERRM, TO_CLOB (DBMS_UTILITY.FORMAT_ERROR_BACKTRACE));
            RAISE;
    END adjust_salary;

    ----------------------------------------------------------------------------
    -- full workflow
    ----------------------------------------------------------------------------
    PROCEDURE run_all IS
        v_rc SYS_REFCURSOR;
        v_emp_id NUMBER;
        v_emp_no VARCHAR2 (30);
        v_emp_name VARCHAR2 (100);
        v_job_title VARCHAR2 (100);
        v_salary NUMBER;
        v_bonus NUMBER;
        v_dept_name VARCHAR2 (100);
        v_sales NUMBER;
        v_rn NUMBER;
        v_total_cnt NUMBER;
        v_ratio NUMBER;
    BEGIN
        seed_extra_rows (7);
        adjust_salary (30, 0.08, FALSE);
        adjust_salary (40, 0.05, FALSE);
        v_ratio := calc_comp_ratio (1, 300000);
        write_log ('INFO', 'run_all', 'Comp ratio for emp_id=1 => ' || TO_CHAR (v_ratio));
        v_rc := get_emp_cursor (30, 'ACTIVE');
        LOOP
            FETCH v_rc
            INTO v_emp_id,
                v_emp_no,
                v_emp_name,
                v_job_title,
                v_salary,
                v_bonus,
                v_dept_name,
                v_sales,
                v_rn,
                v_total_cnt;
            EXIT WHEN v_rc%NOTFOUND;
            IF v_rn <= 3 THEN
                write_log ('DEBUG', 'run_all', 'Top row: ' || v_emp_no || ', salary=' || v_salary || ', sales=' || NVL (v_sales, 0));
            END IF;
        END LOOP;
        CLOSE v_rc;
    EXCEPTION
        WHEN OTHERS THEN
            IF v_rc%ISOPEN THEN
                CLOSE v_rc;
            END IF;
            write_log ('ERROR', 'run_all', SQLERRM, TO_CLOB (DBMS_UTILITY.FORMAT_ERROR_STACK));
            RAISE;
    END run_all;
END qt_pkg_extreme;
/

SHOW ERRORS

--------------------------------------------------------------------------------
-- BASIC PACKAGE EXECUTION
--------------------------------------------------------------------------------

BEGIN
    qt_pkg_extreme.run_all;
END;
/

--------------------------------------------------------------------------------
-- EXTREME QUERY 1: VERY DEEP WITH + CORRELATED + ANALYTIC + CASE
--------------------------------------------------------------------------------

WITH dept_tree AS (
    SELECT
        d.dept_id,
        d.parent_dept_id,
        d.dept_code,
        d.dept_name,
        LEVEL AS lvl,
        SYS_CONNECT_BY_PATH (d.dept_code, '/') AS dept_path
    FROM qt_dept d
    START WITH d.parent_dept_id IS NULL
    CONNECT BY PRIOR d.dept_id = d.parent_dept_id
),
emp_base AS (
    SELECT
        e.emp_id,
        e.dept_id,
        e.mgr_emp_id,
        e.emp_no,
        e.emp_name,
        e.job_title,
        e.salary,
        e.bonus,
        e.hire_date,
        e.status_code,
        CASE
            WHEN e.salary >= 180000 THEN 'EXEC'
            WHEN e.salary >= 130000 THEN 'LEAD'
            WHEN e.salary >= 90000 THEN 'SENIOR'
            ELSE 'STAFF'
        END AS salary_band
    FROM qt_emp e
),
sales_agg AS (
    SELECT
        s.emp_id,
        s.dept_id,
        s.sale_year,
        SUM (s.sale_amount) AS total_sales,
        AVG (s.sale_amount) AS avg_sales,
        MAX (s.sale_amount) AS max_sales,
        MIN (s.sale_amount) AS min_sales
    FROM qt_sales s
    GROUP BY s.emp_id,
        s.dept_id,
        s.sale_year
),
joined_data AS (
    SELECT
        eb.emp_id,
        eb.dept_id,
        -- 추가
        eb.emp_no,
        eb.emp_name,
        eb.job_title,
        eb.salary,
        eb.bonus,
        eb.hire_date,
        eb.status_code,
        eb.salary_band,
        dt.dept_code,
        dt.dept_name,
        dt.dept_path,
        sa.sale_year,
        sa.total_sales,
        sa.avg_sales,
        sa.max_sales,
        sa.min_sales,
        (
            SELECT COUNT (*)
            FROM qt_emp c
            WHERE c.mgr_emp_id = eb.emp_id
        ) AS child_cnt,
        (
            SELECT MAX (x.salary)
            FROM qt_emp x
            WHERE x.dept_id = eb.dept_id
                AND x.emp_id <> eb.emp_id
        ) AS dept_other_max_salary
    FROM emp_base eb
    JOIN dept_tree dt
        ON dt.dept_id = eb.dept_id
    LEFT JOIN sales_agg sa
        ON sa.emp_id = eb.emp_id
        AND sa.dept_id = eb.dept_id
)
SELECT
    j.*,
    DENSE_RANK () OVER (PARTITION BY j.sale_year ORDER BY j.total_sales DESC NULLS LAST) AS sales_rank,
    RANK () OVER (PARTITION BY j.dept_code ORDER BY j.salary DESC NULLS LAST) AS salary_rank_in_dept,
    SUM (NVL (j.total_sales, 0)) OVER (PARTITION BY j.dept_code ORDER BY j.sale_year ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_dept_sales,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM qt_sales s2
            WHERE s2.emp_id = j.emp_id
                AND s2.sale_amount > (
                SELECT AVG (s3.sale_amount)
                FROM qt_sales s3
                WHERE s3.dept_id = j.dept_id
                    AND s3.sale_year = j.sale_year
            )
        ) THEN 'ABOVE_DEPT_AVG_EXISTS'
        ELSE 'NO_ABOVE_DEPT_AVG'
    END AS sales_flag
FROM joined_data j
WHERE NVL (j.total_sales, 0) >= (
    SELECT AVG (NVL (x.total_sales, 0))
    FROM joined_data x
    WHERE x.sale_year = j.sale_year
)
ORDER BY j.sale_year,
    sales_rank,
    j.emp_id;
/

--------------------------------------------------------------------------------
-- EXTREME QUERY 2: PIVOT + UNPIVOT + INLINE VIEWS
--------------------------------------------------------------------------------

WITH src AS (
    SELECT
        s.emp_id,
        s.sale_year,
        s.sale_month,
        s.sale_amount
    FROM qt_sales s
    WHERE s.sale_year IN (2023, 2024)
),
pivoted AS (
    SELECT *
    FROM src PIVOT (SUM (sale_amount)
    FOR sale_month IN (1 AS M01, 2 AS M02, 3 AS M03, 4 AS M04, 5 AS M05, 6 AS M06))
),
unp AS (
    SELECT
        emp_id,
        sale_year,
        month_code,
        month_amt
    FROM pivoted UNPIVOT INCLUDE NULLS (month_amt
    FOR month_code IN (M01 AS 'M01', M02 AS 'M02', M03 AS 'M03', M04 AS 'M04', M05 AS 'M05', M06 AS 'M06'))
)
SELECT
    u.emp_id,
    e.emp_no,
    e.emp_name,
    u.sale_year,
    u.month_code,
    u.month_amt
FROM unp u
JOIN qt_emp e
    ON e.emp_id = u.emp_id
ORDER BY u.emp_id,
    u.sale_year,
    u.month_code;
/

--------------------------------------------------------------------------------
-- EXTREME QUERY 3: MODEL CLAUSE
--------------------------------------------------------------------------------

SELECT dept_id,
    sale_year,
    sale_month,
    sale_amount,
    projected_amount
FROM (
        SELECT dept_id,
            sale_year,
            sale_month,
            SUM (sale_amount) AS sale_amount,
            CAST (NULL AS NUMBER) AS projected_amount
        FROM qt_sales
        WHERE sale_year = 2024
        GROUP BY dept_id,
            sale_year,
            sale_month
    )
MODEL PARTITION BY (dept_id) DIMENSION BY (sale_month) MEASURES (sale_year, sale_amount, projected_amount) RULES (projected_amount [ 1 ] = sale_amount [ 1 ] * 1.05, projected_amount [ 2 ] = sale_amount [ 2 ] * 1.05, projected_amount [ 3 ] = (sale_amount [ 1 ] + sale_amount [ 2 ] + sale_amount [ 3 ]) / 3, projected_amount [ 4 ] = NVL (projected_amount [ 3 ], sale_amount [ 4 ]) * 1.02)
ORDER BY dept_id,
    sale_month;
/

--------------------------------------------------------------------------------
-- EXTREME QUERY 4: MERGE WITH COMPLEX SOURCE
--------------------------------------------------------------------------------

MERGE INTO qt_emp tgt
USING (
    SELECT e.emp_id,
        CASE
            WHEN EXISTS (
                SELECT 1
                FROM qt_sales s
                WHERE s.emp_id = e.emp_id
                    AND s.sale_year = 2024
                    AND s.sale_amount > (
                    SELECT AVG (s2.sale_amount)
                    FROM qt_sales s2
                    WHERE s2.dept_id = e.dept_id
                        AND s2.sale_year = 2024
                )
            ) THEN 'ACTIVE'
            ELSE e.status_code
        END AS new_status_code,
        CASE
            WHEN e.salary < 100000 THEN e.salary + 2500
            WHEN e.salary BETWEEN 100000 AND 160000 THEN e.salary + 1500
            ELSE e.salary + 500
        END AS new_salary
    FROM qt_emp e
    WHERE e.status_code IN ('ACTIVE', 'LEAVE')
) src
    ON (tgt.emp_id = src.emp_id)
    WHEN MATCHED THEN
UPDATE
SET tgt.status_code = src.new_status_code,
    tgt.salary = src.new_salary,
    tgt.updated_at = SYSTIMESTAMP
WHERE NVL (tgt.status_code, 'X') <> NVL (src.new_status_code, 'X')
    OR NVL (tgt.salary, - 1) <> NVL (src.new_salary, - 1);
/

--------------------------------------------------------------------------------
-- EXTREME QUERY 5: HIERARCHICAL + SCALAR SUBQUERY + XML-LIKE STRING BUILDING
--------------------------------------------------------------------------------

SELECT LEVEL AS lvl,
    LPAD (' ', (LEVEL - 1) * 2) || d.dept_name AS dept_tree_name,
    d.dept_code,
    (
        SELECT COUNT (*)
        FROM qt_emp e
        WHERE e.dept_id = d.dept_id
    ) AS emp_cnt,
    (
        SELECT LISTAGG (x.emp_no || ':' || x.emp_name, ', ') WITHIN
            GROUP (ORDER BY x.emp_no)
        FROM (
                SELECT e2.emp_no,
                    e2.emp_name
                FROM qt_emp e2
                WHERE e2.dept_id = d.dept_id
                    AND ROWNUM <= 5
            ) x
    ) AS sample_emps
FROM qt_dept d
START WITH d.parent_dept_id IS NULL
CONNECT BY PRIOR d.dept_id = d.parent_dept_id
ORDER SIBLINGS BY d.dept_code;
/

--------------------------------------------------------------------------------
-- EXTREME QUERY 6: CURSOR EXPRESSION
--------------------------------------------------------------------------------

SELECT d.dept_id,
    d.dept_name,
    CURSOR (
        SELECT e.emp_id,
            e.emp_no,
            e.emp_name,
            CURSOR (
                SELECT s.sale_year,
                    SUM (s.sale_amount) AS total_sales
                FROM qt_sales s
                WHERE s.emp_id = e.emp_id
                GROUP BY s.sale_year
                ORDER BY s.sale_year
            ) AS sales_cur
        FROM qt_emp e
        WHERE e.dept_id = d.dept_id
        ORDER BY e.emp_id
    ) AS emp_cur
FROM qt_dept d
ORDER BY d.dept_id;
/

--------------------------------------------------------------------------------
-- EXTREME PL/SQL BLOCK 1: NESTED DECLARE/BEGIN/EXCEPTION + DYNAMIC SQL
--------------------------------------------------------------------------------

DECLARE
    TYPE t_varchar_tab IS TABLE OF VARCHAR2 (100) INDEX BY PLS_INTEGER;
    v_names t_varchar_tab;
    v_count NUMBER := 0;
    v_stmt VARCHAR2 (32767);
    v_max_salary NUMBER;
    v_dept_id NUMBER := 30;
    v_err_msg VARCHAR2 (4000);
    v_err_bt VARCHAR2 (4000);
BEGIN
    v_names (1) := 'ALICE';
    v_names (2) := 'BOB';
    v_names (3) := 'CAROL';
    v_stmt := 'SELECT MAX(salary) ' || 'FROM qt_emp ' || 'WHERE dept_id = :x ' || '  AND emp_name IN (SELECT COLUMN_VALUE FROM TABLE(sys.odcivarchar2list(:a,:b,:c)))';
    EXECUTE IMMEDIATE v_stmt
    INTO v_max_salary
        USING v_dept_id,
        v_names (1),
        v_names (2),
        v_names (3);
    BEGIN
        IF v_max_salary IS NOT NULL THEN
            INSERT INTO qt_audit_log (log_level, module_name, message_text, extra_text)
            VALUES ('INFO', 'anonymous_block_1', 'Max salary=' || TO_CHAR (v_max_salary), TO_CLOB ('Dynamic SQL executed successfully'));
        ELSE
            INSERT INTO qt_audit_log (log_level, module_name, message_text, extra_text)
            VALUES ('WARN', 'anonymous_block_1', 'No max salary found', TO_CLOB ('No matching rows'));
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            v_err_msg := SQLERRM;
            v_err_bt := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
            INSERT INTO qt_audit_log (log_level, module_name, message_text, extra_text)
            VALUES ('ERROR', 'anonymous_block_1_nested', v_err_msg, TO_CLOB (v_err_bt));
            RAISE;
    END;
    SELECT COUNT (*)
    INTO v_count
    FROM qt_audit_log
    WHERE module_name LIKE 'anonymous_block_1%';
    DBMS_OUTPUT.PUT_LINE ('anonymous_block_1 log count=' || v_count);
END;
/
/

--------------------------------------------------------------------------------
-- EXTREME PL/SQL BLOCK 2: LABELS + MULTI-LEVEL LOOPS + CASE
--------------------------------------------------------------------------------

DECLARE
    v_total NUMBER := 0;
BEGIN
    <<outer_loop>>
    FOR i IN 1..4 LOOP
        <<middle_loop>>
        FOR j IN 1..3 LOOP
            <<inner_loop>>
            FOR k IN 1..2 LOOP
                v_total := v_total +
                CASE
                    WHEN MOD (i + j + k, 2) = 0 THEN
                        i * j * k
                    ELSE
                        i + j + k
                END;
                EXIT inner_loop WHEN v_total > 200;
            END LOOP inner_loop;
            EXIT middle_loop WHEN v_total > 200;
        END LOOP middle_loop;
        EXIT outer_loop WHEN v_total > 200;
    END LOOP outer_loop;
    INSERT INTO qt_audit_log (log_level, module_name, message_text, extra_text)
    VALUES ('INFO', 'anonymous_block_2', 'Final total=' || v_total, TO_CLOB ('Nested loop stress test completed'));
END;
/

--------------------------------------------------------------------------------
-- EXTREME SELECT 7: MONSTER NESTED INLINE QUERIES
--------------------------------------------------------------------------------

SELECT *
FROM (
        SELECT z.*,
            ROW_NUMBER () OVER (PARTITION BY z.dept_code ORDER BY z.weighted_score DESC NULLS LAST, z.emp_id) AS dept_rn
        FROM (
                SELECT y.emp_id,
                    y.emp_no,
                    y.emp_name,
                    y.dept_code,
                    y.dept_name,
                    y.total_sales,
                    y.avg_sales,
                    y.salary,
                    y.bonus,
                    y.child_cnt,
                    ROUND ((NVL (y.total_sales, 0) * 0.45 + NVL (y.salary, 0) * 0.35 + NVL (y.bonus, 0) * 0.10 + NVL (y.child_cnt, 0) * 1000 * 0.10) / NULLIF (
                        CASE
                            WHEN y.status_code = 'ACTIVE' THEN 1
                            WHEN y.status_code = 'LEAVE' THEN 1.15
                            ELSE 1.30
                        END, 0), 2) AS weighted_score
                FROM (
                        SELECT x.emp_id,
                            x.emp_no,
                            x.emp_name,
                            x.dept_code,
                            x.dept_name,
                            x.status_code,
                            x.salary,
                            x.bonus,
                            x.child_cnt,
                            (
                                SELECT SUM (s1.sale_amount)
                                FROM qt_sales s1
                                WHERE s1.emp_id = x.emp_id
                                    AND s1.sale_year = 2024
                            ) AS total_sales,
                            (
                                SELECT AVG (s2.sale_amount)
                                FROM qt_sales s2
                                WHERE s2.emp_id = x.emp_id
                                    AND s2.sale_year = 2024
                            ) AS avg_sales
                        FROM (
                                SELECT e.emp_id,
                                    e.emp_no,
                                    e.emp_name,
                                    d.dept_code,
                                    d.dept_name,
                                    e.status_code,
                                    e.salary,
                                    e.bonus,
                                    (
                                        SELECT COUNT (*)
                                        FROM qt_emp c
                                        WHERE c.mgr_emp_id = e.emp_id
                                    ) AS child_cnt
                                FROM qt_emp e
                                JOIN qt_dept d
                                    ON d.dept_id = e.dept_id
                                WHERE EXISTS (
                                        SELECT 1
                                        FROM qt_sales s
                                        WHERE s.emp_id = e.emp_id
                                            AND s.sale_year = 2024
                                    )
                            ) x
                    ) y
            ) z
    )
WHERE dept_rn <= 3
ORDER BY dept_code,
    dept_rn,
    emp_id;
/

--------------------------------------------------------------------------------
-- FINAL VERIFICATION QUERIES
--------------------------------------------------------------------------------

SELECT COUNT (*) AS emp_cnt
FROM qt_emp;

SELECT COUNT (*) AS sales_cnt
FROM qt_sales;

SELECT COUNT (*) AS audit_cnt
FROM qt_audit_log;

SELECT *
FROM qt_emp_summary_v
ORDER BY sale_year,
    sales_rank,
    emp_id;
/