CREATE TABLE OQT_CLOB_FIX_T (id NUMBER PRIMARY KEY, doc CLOB, ndoc NCLOB, xdoc XMLTYPE)
LOB (doc) STORE AS BASICFILE
LOB (ndoc) STORE AS BASICFILE
XMLTYPE COLUMN xdoc STORE AS BASICFILE CLOB;

DECLARE
  v CLOB;
BEGIN
  DBMS_LOB.CREATETEMPORARY(v, TRUE);
  FOR i IN 1..40 LOOP
    DBMS_LOB.WRITEAPPEND(v, 3200, RPAD('0123456789AbCdEfGhIjKlMnOpQrStUv', 3200, '0123456789AbCdEfGhIjKlMnOpQrStUv'));
  END LOOP;
  INSERT INTO OQT_CLOB_FIX_T (id, doc, ndoc, xdoc)
  VALUES (1, v, TO_NCLOB(v), XMLTYPE('<root><payload>' || RPAD('x', 3000, 'x') || '</payload></root>'));
  COMMIT;
  DBMS_LOB.FREETEMPORARY(v);
END;
/

SELECT id, LENGTH(doc) AS doc_len FROM OQT_CLOB_FIX_T ORDER BY id;

SELECT id, doc FROM OQT_CLOB_FIX_T ORDER BY id;

SELECT id, ndoc FROM OQT_CLOB_FIX_T ORDER BY id;

SELECT id, xdoc FROM OQT_CLOB_FIX_T ORDER BY id;

DROP TABLE OQT_CLOB_FIX_T PURGE;
